#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os, fnmatch

print("""#-*- coding: utf-8 -*-
# DO NOT EDIT THIS FILE MANUALLY, IT WILL GO AWAY!

embedsvg = {
""")

for dir in [os.path.join("public"), os.path.join("..", "vi_customizing", "public")]:
	path = os.path.join(dir, "embedsvg")

	try:
		svgs = fnmatch.filter(os.listdir(path), "*.svg")
	except OSError:
		continue

	for svg in svgs:
		key = svg[:-4]
		print("\tu\"\"\"{}\"\"\": u\"\"\"{}\"\"\",".format(key, open(os.path.join(path, svg), "r").read()))

print("}")
