#from widgets.modullist import ModulListWidget
from widgets.topbar import TopBarWidget
from widgets.list import ListWidget
from widgets.edit import EditWidget
from widgets.table import DataTable
from widgets.actionbar import ActionBar
from widgets.tree import TreeWidget
from widgets.hierarchy import HierarchyWidget
from widgets.file import FileWidget
